import { create } from 'zustand';
import type {
  SystemMetrics, ComponentHealth, Task, GenesisEvent, Plugin,
  EpisodicMemoryEntry, SemanticMemoryEntry, WorkingMemoryEntry,
  Proposal, AuditEntry, ModelProvider, SystemState, PageId,
  TaskStatus, TaskStep,
} from '../core/types';
import {
  SYSTEM_METRICS, COMPONENTS, RECENT_EVENTS, MODEL_PROVIDERS,
  createMockTasks, createMockPlugins, createMockMemories,
  createMockProposals, createMockAudit,
} from '../core/constants';
import { kernelClient } from '../core/kernel-client';

let kernelConnected = false;

kernelClient.on('connected', () => {
  kernelConnected = true;
  kernelClient.subscribe('system.health');
  kernelClient.subscribe('cog.task.*');
  kernelClient.subscribe('perc.*');
  kernelClient.subscribe('learn.*');
  kernelClient.requestSnapshot();
});

kernelClient.on('kernel.snapshot', (payload) => {
  const sys = useSystemStore.getState();
  useSystemStore.setState({
    system: {
      ...sys.system,
      uptime: (payload.lifecycle as Record<string, unknown>)?.transitionCount as number ?? 0,
      state: ((payload.lifecycle as Record<string, unknown>)?.state as SystemState) ?? 'running',
    },
  });
});

// Bridge kernel events to UI state
kernelClient.on('cog.task.received', (p) => {
  const task: Task = {
    id: p.taskId as string,
    title: (p.goal as string)?.substring(0, 60) ?? 'New Task',
    description: (p.goal as string) ?? '',
    status: 'pending' as TaskStatus,
    priority: 'medium',
    phase: 'observe',
    source: 'user',
    createdAt: p.timestamp as number ?? Date.now(),
    steps: [],
    assignedTo: 'axiom',
  };
  useTaskStore.getState().addTask(task);
});

kernelClient.on('cog.task.planned', (p) => {
  const tasks = useTaskStore.getState().tasks;
  const task = tasks.find(t => t.description === (p.goal as string));
  if (task) {
    useTaskStore.setState({
      tasks: tasks.map(t =>
        t.id === task.id
          ? {
              ...t,
              status: 'deciding' as TaskStatus,
              phase: 'decide',
              steps: ((p.steps as Array<{ action: string; riskLevel: string }>) ?? []).map((s, i) => ({
                id: `${t.id}-step-${i}`,
                action: s.action,
                capability: 'infra.text_generation',
                status: 'pending' as const,
                dependencies: [],
              })),
            }
          : t
      ),
    });
  }
});

kernelClient.on('cog.task.step_completed', (p) => {
  const tasks = useTaskStore.getState().tasks;
  useTaskStore.setState({
    tasks: tasks.map(t => ({
      ...t,
      steps: t.steps.map(s =>
        s.id === (p.stepId as string)
          ? { ...s, status: (p.outcome ? 'completed' : 'failed') as TaskStep['status'], result: p.outcome as string, error: p.error as string }
          : s
      ),
    })),
  });
});

kernelClient.on('cog.task.completed', (p) => {
  const tasks = useTaskStore.getState().tasks;
  const metrics = p.metrics as Record<string, number> | undefined;
  useTaskStore.setState({
    tasks: tasks.map(t =>
      t.steps.length > 0
        ? {
            ...t,
            status: (p.outcome === 'success' ? 'completed' : 'failed') as TaskStatus,
            completedAt: Date.now(),
            tokensUsed: metrics?.tokensUsed ?? t.tokensUsed,
            cost: metrics?.cost ?? t.cost,
          }
        : t
    ),
  });
  // Update system metrics
  const sys = useSystemStore.getState();
  useSystemStore.setState({
    system: {
      ...sys.system,
      completedTasks: sys.system.completedTasks + 1,
      tokensUsed: sys.system.tokensUsed + (metrics?.tokensUsed ?? 0),
      totalCost: sys.system.totalCost + (metrics?.cost ?? 0),
    },
  });
});

kernelClient.on('perc.observation.processed', (p) => {
  useSystemStore.getState().addEvent({
    id: crypto.randomUUID?.() ?? `${Date.now()}`,
    stream: 'perc',
    category: 'perc',
    type: 'perc.observation.processed',
    timestamp: Date.now(),
    sequence: 0,
    payload: p,
    source: 'eve',
  });
});

kernelClient.on('perc.reflection.completed', (p) => {
  useSystemStore.getState().addEvent({
    id: crypto.randomUUID?.() ?? `${Date.now()}`,
    stream: 'perc',
    category: 'perc',
    type: 'perc.reflection.completed',
    timestamp: Date.now(),
    sequence: 0,
    payload: p,
    source: 'eve',
  });
});

kernelClient.on('learn.proposal.created', (p) => {
  const proposal: Proposal = {
    id: p.proposalId as string,
    type: (p.type as Proposal['type']) ?? 'strategy_change',
    riskLevel: (p.riskLevel as Proposal['riskLevel']) ?? 'low',
    status: 'draft',
    description: `ADAM Proposal: ${p.type as string}`,
    rationale: 'Auto-generated by ADAM from experience consolidation',
    evidence: [],
    change: {},
    rollback: {},
    createdBy: 'adam',
    createdAt: Date.now(),
    confidence: 0.6,
    estimatedImpact: { metric: 'success_rate', currentValue: 0.7, predictedValue: 0.75, confidence: 0.5 },
  };
  useProposalStore.getState().addProposal(proposal);
});

kernelClient.on('learn.meta.report', (p) => {
  const metrics = p.metrics as Record<string, number> | undefined;
  if (metrics) {
    const sys = useSystemStore.getState();
    useSystemStore.setState({
      system: {
        ...sys.system,
        successRate: metrics.proposalAcceptanceRate ?? sys.system.successRate,
      },
    });
  }
});

// Start connection (non-blocking)
try {
  kernelClient.connect();
} catch {
  console.log('[Store] Kernel not available — using mock data');
}

// ─── System Store ─────────────────────────────────────────────────

interface SystemStore {
  // State
  system: SystemMetrics;
  components: ComponentHealth[];
  events: GenesisEvent[];
  providers: ModelProvider[];
  page: PageId;

  // Actions
  setPage: (page: PageId) => void;
  updateComponentHealth: (id: string, update: Partial<ComponentHealth>) => void;
  addEvent: (event: GenesisEvent) => void;
  setSystemState: (state: SystemState) => void;
  tick: () => void;
}

export const useSystemStore = create<SystemStore>((set, get) => ({
  system: SYSTEM_METRICS,
  components: COMPONENTS,
  events: RECENT_EVENTS,
  providers: MODEL_PROVIDERS,
  page: 'dashboard',

  setPage: (page) => set({ page }),

  updateComponentHealth: (id, update) =>
    set((s) => ({
      components: s.components.map((c) =>
        c.id === id ? { ...c, ...update, lastHeartbeat: Date.now() } : c
      ),
    })),

  addEvent: (event) =>
    set((s) => ({
      events: [event, ...s.events].slice(0, 100),
    })),

  setSystemState: (state) =>
    set((s) => ({ system: { ...s.system, state } })),

  tick: () => {
    if (kernelConnected) return; // Don't simulate when kernel is live
    const s = get();
    set({
      system: { ...s.system, uptime: s.system.uptime + 1 },
      components: s.components.map((c) => ({
        ...c,
        uptime: c.uptime + 1,
        cpuPercent: Math.max(1, Math.min(95, c.cpuPercent + (Math.random() - 0.5) * 8)),
        memoryMB: Math.max(16, c.memoryMB + (Math.random() - 0.5) * 4),
        lastHeartbeat: Date.now(),
      })),
    });
  },
}));

// ─── Task Store ────────────────────────────────────────────────────

interface TaskStore {
  tasks: Task[];
  selectedTaskId: string | null;
  setSelectedTask: (id: string | null) => void;
  advanceTask: (taskId: string) => void;
  addTask: (task: Task) => void;
}

export const useTaskStore = create<TaskStore>((set) => ({
  tasks: kernelConnected ? [] : createMockTasks(),
  selectedTaskId: null,

  setSelectedTask: (id) => set({ selectedTaskId: id }),

  advanceTask: (taskId) => {
    if (kernelConnected) return; // Kernel handles advancement
    set((s) => ({
      tasks: s.tasks.map((t) => {
        if (t.id !== taskId) return t;
        const phases: Task['phase'][] = ['observe', 'orient', 'decide', 'reflect', 'simulate', 'act'];
        const si = phases.indexOf(t.phase);
        if (si < phases.length - 1) return { ...t, phase: phases[si + 1] };
        return { ...t, status: 'completed' as const, completedAt: Date.now() };
      }),
    }));
  },

  addTask: (task) =>
    set((s) => ({
      tasks: [task, ...s.tasks],
    })),
}));

// ─── Plugin Store ──────────────────────────────────────────────────

interface PluginStore {
  plugins: Plugin[];
  selectedPluginId: string | null;
  setSelectedPlugin: (id: string | null) => void;
  togglePluginLoad: (id: string) => void;
}

export const usePluginStore = create<PluginStore>((set) => ({
  plugins: createMockPlugins(),
  selectedPluginId: null,

  setSelectedPlugin: (id) => set({ selectedPluginId: id }),

  togglePluginLoad: (id) =>
    set((s) => ({
      plugins: s.plugins.map((p) => {
        if (p.id !== id) return p;
        const newStatus = p.status === 'running' ? 'unloaded' as const : 'running' as const;
        return { ...p, status: newStatus };
      }),
    })),
}));

// ─── Memory Store ──────────────────────────────────────────────────

interface MemoryStore {
  workingMemories: WorkingMemoryEntry[];
  episodicMemories: EpisodicMemoryEntry[];
  semanticMemories: SemanticMemoryEntry[];
  selectedMemoryId: string | null;
  memoryTab: 'working' | 'episodic' | 'semantic';
  setMemoryTab: (tab: 'working' | 'episodic' | 'semantic') => void;
  setSelectedMemory: (id: string | null) => void;
}

export const useMemoryStore = create<MemoryStore>((set) => {
  const mems = createMockMemories();
  return {
    ...mems,
    selectedMemoryId: null,
    memoryTab: 'working',
    setMemoryTab: (tab) => set({ memoryTab: tab }),
    setSelectedMemory: (id) => set({ selectedMemoryId: id }),
  };
});

// ─── Proposal Store ────────────────────────────────────────────────

interface ProposalStore {
  proposals: Proposal[];
  selectedProposalId: string | null;
  setSelectedProposal: (id: string | null) => void;
  approveProposal: (id: string) => void;
  rejectProposal: (id: string) => void;
  addProposal: (p: Proposal) => void;
}

export const useProposalStore = create<ProposalStore>((set) => ({
  proposals: kernelConnected ? [] : createMockProposals(),
  selectedProposalId: null,

  setSelectedProposal: (id) => set({ selectedProposalId: id }),

  approveProposal: (id) => {
    if (kernelConnected) {
      kernelClient.approveProposal(id);
    }
    set((s) => ({
      proposals: s.proposals.map((p) =>
        p.id === id
          ? { ...p, status: 'canary' as const, deploymentPhase: 'canary' as const, deploymentProgress: 0, approvalBy: 'operator' }
          : p
      ),
    }));
  },

  rejectProposal: (id) => {
    if (kernelConnected) {
      kernelClient.rejectProposal(id);
    }
    set((s) => ({
      proposals: s.proposals.map((p) =>
        p.id === id ? { ...p, status: 'rejected' as const } : p
      ),
    }));
  },

  addProposal: (proposal) =>
    set((s) => ({
      proposals: [proposal, ...s.proposals],
    })),
}));

// ─── Audit Store ────────────────────────────────────────────────────

interface AuditStore {
  entries: AuditEntry[];
}

export const useAuditStore = create<AuditStore>(() => ({
  entries: createMockAudit(),
}));
